lenguage: python
env:
  global:
    - PKG_NAME="ngskit"

python:
  - "2.7"
  - "3.4"

script:
  - pip install --user pytest pytest-cov
  - py.test -vvv

after_success:
  - echo "Success!"

after_failure:
  - echo "Failure!"
after_script:
  - echo "X_X"
