lenguage: python
env:
  global:
    - PKG_NAME="ngskit"

python:
  - "2.7"
  - "3.4"

install:
  - pip install --user pytest pytest-cov
  - pip install --user coveralls
  - pip install --user python-levenshtein
  - python setup.py -q install

script:

  - coverage run --source=ngskit setup.py test

after_success:
  - coveralls


after_failure:
  - echo "Failure!"
after_script:
  - echo "X_X"
