sudo: true
language: python
env:
  global:
    - PKG_NAME="ngskit"

python:
  - "2.7"
  - "3.4"

install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install python-levenshtein
  - pip install setuptools
  - pip install .

script:

  - pytest

after_success:
  - coveralls


after_failure:
  - echo "Failure!"
after_script:
  - echo "X_X"
