package:
  name: ngskit
  version: "0.0.1"

source:
  git_url: https://github.com/kimlaborg/NGSKit.git

requirements:
  build:
    - python
    - setuptools
    - python-levenshtein

  run:
    - python

test:
  imports:
    - ngskit

about:
  home:
  license:
  license_file:
