package:
  name: ngskit
  version: "0.1"

build:
  number: 0
  script: 
    - python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools


  run:
    - python
    - python-levenshtein
    - pandas
    - scikit-learn



test:
  commands:
    - py.test

about:
  home: https://github.com/kimlab/ngskit
  license: MIT
  license_file:
